### ISSUE TITLE
Deploying DCOS Enterprise 1.12.3 yields broken deployment

### ISSUE THREAD

**Issue by sbaier1** [dcos/dcos-ansible#16]
Trying to set up an enterprise cluster on CentOS7 on top of OpenStack. I was previously successful in doing so for open source DCOS 1.12.1 and upgraded successfully to 1.12.3 with a very similar configuration to the one below, however i cannot do the same to deploy enterprise using these playbooks (using the current HEAD on master).

Also: is it not possible to upgrade an open source cluster to an enterprise cluster?

Steps i performed:
- Deploy 8 instances of a CentOS7 image
- Use `dcos-ee-8` as my bootstrap node
- installed ansible on the bootstrap node
- checked out the repository and configured it as shown below
- ran the playbook
- copied the license to the genconf folder after the playbook errored (where should the license be placed beforehand? could not find any information regarding this)
- ran the playbook again

The playbooks complete successfully, but the services on the master do not start correctly.

For example mesos-master fails to start and is stuck in a crash loop, crashing when attempting to start:
```
Failed to load flag 'domain': Failed to load value '{"fault_domain":{"region":{"name": onprem-1},"zone":{"name": onprem-1a}}}': syntax error at line 1 near: onprem-1},"zone":{"name": onprem-1a}}}
```

My `group_vars/all/dcos.yaml`:
```
---
dcos:
  download: "http://downloads.mesosphere.com/dcos-enterprise/stable/1.12.3/dcos_generate_config.ee.sh"
  version: "1.12.3"
  # version_to_upgrade_from: "1.12.3"
  # image_commit: "acc9fe548aea5b1b5b5858a4b9d2c96e07eeb9de"
  enterprise_dcos: true

  selinux_mode: permissive

  config:
    # This is a direct yaml representation of the DC/OS config.yaml
    # Please see https://docs.mesosphere.com/1.12/installing/production/advanced-configuration/configuration-reference/
    # for parameter reference.
    cluster_name: "dc-cluster01"
    security: permissive
    bootstrap_url: http://dcos-ee-8:8080
    exhibitor_storage_backend: static
    ip_detect_contents: "#!/bin/sh\ncurl -fsSL http://169.254.169.254/latest/meta-data/local-ipv4\n"
    ip_detect_public_contents: "#!/bin/sh\ncurl -fsSL http://169.254.169.254/latest/meta-data/public-ipv4\n"
    # dns fix
    dns_search: office.dc2 novalocal
    resolvers:
    - 172.16.0.2
    - 172.16.0.3    
    master_discovery: static
    master_list:
      - 172.16.0.28
      - 172.16.0.34
      - 172.16.0.29
```

Where the masters correspond to the masters (dcos-ee-1, 2 and 3 as follows)

Inventory:
```
[bootstraps]
dcos-ee-8

[masters]
dcos-ee-1
dcos-ee-2
dcos-ee-3

[agents_private]
dcos-ee-4
dcos-ee-5
dcos-ee-6

[agents_public]
dcos-ee-7

[bootstraps:vars]
node_type=bootstrap

[masters:vars]
node_type=master
dcos_legacy_node_type_name=master

[agents_private:vars]
node_type=agent
dcos_legacy_node_type_name=slave

[agents_public:vars]
node_type=agent_public
dcos_legacy_node_type_name=slave_public

[agents:children]
agents_private
agents_public

[common:children]
bootstraps
masters
agents
agents_public
```
