### ISSUE TITLE
Resolvers value not being used in ansible scripts

### ISSUE THREAD

**Issue by pkaramol** [dcos/dcos-ansible#5]
Here is my `dcos.yml` file:

```
dcos:
  download: "https://downloads.dcos.io/dcos/stable/dcos_generate_config.sh"
  version: "1.12.1"
  # version_to_upgrade_from: "1.12.0"
  # image_commit: "acc9fe548aea5b1b5b5858a4b9d2c96e07eeb9de"
  enterprise_dcos: false
  selinux_mode: permissive

  config:
    # This is a direct yaml representation of the DC/OS config.yaml
    # Please see https://docs.mesosphere.com/1.12/installing/production/advanced-configuration/configuration-reference/
    # for parameter reference.
    cluster_name: "dcos-dev-mycompany"
    security: strict
    bootstrap_url: http://bootstrap-dcos.mycompany.local:8080
    exhibitor_storage_backend: static
    master_discovery: static
    ip_detect: ens33
    dns_search: mycompany.local
    resolvers:
      - 10.18.0.1
    master_list:
      - 10.18.0.3
```

However, whenever the bootstrap script runs, the resolvers always keep being `8.8.8.8` and `8.8.4.4`

```
[root@master01 default]# cat /etc/resolv.conf
# Generated by gen_resolvconf.py. Do not edit.
# Change configuration options by changing DC/OS cluster configuration.
# This file must be overwritten regularly for proper cluster operation around
# master failure.

options timeout:1
options attempts:3

nameserver 8.8.8.8
nameserver 8.8.4.4

```
